package com.herpro.livedata.model;

import com.herpro.livedata.CategoriesRepository;

public class Category {
    private final int id;
    private final String name;

    public Category(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public Category(String name) {
        this(CategoriesRepository.autogeneratedId, name);
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    // TODO: Más atributos...
}
